### ISSUE TITLE
Milestone: 5.6

### ISSUE THREAD

**Issue by ericanderson** [palantir/conjure-typescript#240]
- [ ] Support generating service functions
- [ ] Support custom tsconfig file (or multiple formats published)
- [ ] Remove trailing undefineds
